---
title: "Means and standard error plotting"
author: "Bill Perry"
date: "2019/10/26"
output:
  html_document:
    theme: cosmo
    toc: TRUE
    toc_float: TRUE
---

## Load libraries

```{r, message=FALSE, warning=FALSE}

# install.packages("devtools")
# devtools::install_github("thomasp85/patchwork")

# load the libraries each time you restart R
library("readxl") # read in excel files
library("tidyverse") # dplyr and piping and ggplot etc
library("lubridate") # dates and times
library("scales") # scales on ggplot ases
library("skimr") # quick summary stats
library("janitor") # clean up excel imports
library("patchwork") # multipanel graphs
```


##Read files

```{r}
# lets read in a new file to add some complexity for fun
lakes.df <- read_csv("data/Reduced_Lake_Long_Genus_Species.csv")


```

```{r}
# now we can do some more fun stuff
# what if we wanted to just look at the mean density by year?
# we can do this in ggplot

# lets make a year column
lakes.df <- lakes.df %>%
  mutate( year = year(date))

```



```{r}
# now for the plot
ggplot(lakes.df, aes(year, color=group)) + 
  stat_summary(aes(y = org_l),
               fun.y = mean, na.rm = TRUE,
               geom = "point",
               size = 3) + 
  stat_summary(aes(y = org_l),
               fun.y = mean, na.rm = TRUE,
               geom = "line",
               size = 1) +
  stat_summary(aes(y = org_l),
               fun.data = mean_se, na.rm = TRUE,
               geom = "errorbar",
               width = 0.2) +
  labs(x = "Date", y = "Animals (Number per Liter)") +
  scale_color_manual(name = "Group", 
                     values = c("blue", "red"),
                     labels = c("Cladoceran", "Copepod"))
```


```{r}
# we can offset the points so they dont overlap
ggplot(lakes.df, aes(year, color=group)) + 
  stat_summary(aes(y = org_l),
               fun.y = mean, na.rm = TRUE,
               geom = "point",
               size = 3, 
               position = position_dodge(0.2)) +
  stat_summary(aes(y = org_l),
               fun.y = mean, na.rm = TRUE,
               geom = "line",
               size = 1, 
               position = position_dodge(0.2)) +
  stat_summary(aes(y = org_l),
               fun.data = mean_se, na.rm = TRUE,
               geom = "errorbar",
               width = 0.2, 
               position = position_dodge(0.2)) +
  labs(x = "Date", y = "Animals (Number per Liter)") +
  scale_color_manual(name = "Group", 
                     values = c("blue", "red"),
                     labels = c("Cladoceran", "Copepod"))

```





<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-88373117-6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-88373117-6');
</script>
